package domain.model.value

enum class ConversationState {
    INITIAL,

    USERS_LIST_DISPLAYED,
    USER_PHONE_NUMBER_REQUESTED,
    USER_NAME_REQUESTED,

    COMPETITIONS_LIST_DISPLAYED,

    COMPETITION_NAME_REQUESTED,
    COMPETITION_VINE_TYPE_REQUESTED,
    COMPETITION_EXPERTS_SELECTION_REQUESTED,
    COMPETITION_CATEGORIES_SELECTION_REQUESTED,
    COMPETITION_VINES_REQUESTED,

    COMPETITION_VINE_PICK_REQUESTED,
    COMPETITION_CATEGORY_PICK_REQUESTED,
    COMPETITION_VINE_MARK_REQUESTED,
}